### ISSUE TITLE
Update runtime to nodejs12.x

### ISSUE THREAD

**Issue by mdgreenwald** [sinovi/lambda-edge-remove-trailing-slash#1]
The runtime `nodejs8.10` is no longer supported by AWS Lambda:

https://github.com/sinovi/lambda-edge-remove-trailing-slash/blob/4762cf2f2bc9f34b9d937c6585431fd453fe11da/serverless.yaml#L9

The YAML works fine if the runtime is updated to:

```yaml
Runtime: nodejs12.x
```

**Comment by hicksy** [comment]
Sorry it's taken a year to respond to this 🤦 

We've updated to `nodejs12` now 👍

**Comment by hicksy** [comment]
https://console.aws.amazon.com/serverlessrepo/home?region=us-east-1#/published-applications/arn:aws:serverlessrepo:us-east-1:951661612909:applications~LambdaEdgeRemoveTrailingSlash

**Comment by mdgreenwald** [comment]
No problem! Thanks for updating!
