### ISSUE TITLE
Too many redirect Error

### ISSUE THREAD

**Issue by anjali89r** [sinovi/lambda-edge-remove-trailing-slash#3]
I rewrote this in nodejs12.x and deployed in my AWS account to test it. When hitting the URL with / (eg: cloudfrontdl.net/page1/) it redirects and then throws too many redirect error.
Can you please let me know how you have resolved it?

**Comment by hicksy** [comment]
Hi Anjali - sorry we've taken ages to respond to this. 

Hope by now you might have resolved the problem. 

But if not, to be able to help debug we'd need to know a little more about the origin server and whether any redirects are occurring there / anything else occurring on the stack

We've not seen this on any of our implementations (which all use S3 as a CF origin)

**Comment by vaitko** [comment]
This is definitely what's happening in my case as well. Redirects happen between 301<->302

example.com redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

**Comment by steve-fenton-octopus** [comment]
If you are using Cloudfront over S3 static website hosting, S3 will be trying to add the trailing slash. This causes the redirect loop:

- `/example/` -> Cloudfront 301 to `/example`
- `/example` -> S3 static webiste 301 to `/example/`
- Repeat forever

So far, the only way I can find to stop S3 adding the trailing slash is to *add metadata to every index.html file* to [specify it's address without the slash](https://repost.aws/knowledge-center/s3-static-website-url-trailing-slash).

**Comment by hicksy** [comment]
Hi @steve-fenton-octopus , yes we had this issue when we migrated our s3 hosted site from a custom static site builder we hand-balled ourselves, which created S3 objects like `articles/some-article.html` to Eleventy which creates objects like `articles/some-article/index.html`. 

I keep meaning to document, but to achieve the trailing slash removal for S3 sites that use sub directories with an `index.html`, as 11ty and perhaps others do, you can do the following:

1. Create a new CloudFront function with the following code 

```
function handler(event) {
    var request = event.request;
    var uri = request.uri;
    
    var params = '';
    if(('querystring' in request) && (request.querystring.length > 0)) {
        params = '?'+request.querystring;
    }
    
    if(uri.endsWith('/')) {
        if(uri !== '/') {
            var response = {
                statusCode: 301,
                statusDescription: 'Permanently moved',
                headers:
                { "location": { "value": `${uri.slice(0, -1) + params}` } } // remove trailing slash
            }
    
            return response;    
        }
        
        
    }
    //Check whether the URI is missing a file extension.
    else if (!uri.includes('.')) {
        request.uri += '/index.html';
    }
    
    

    return request;
}
```

2. Publish your new function

3. Modify your Cloudfront distribution's behaviour and set the published function to run on Viewer request. 

<img width="814" alt="Screenshot 2023-05-16 at 10 31 49" src="https://github.com/sinovi/lambda-edge-remove-trailing-slash/assets/785770/4f76d03c-f29c-4554-b711-b60709ed96ee">


Hopefully, as for us, this will resolve your issue. Let us know how you get on 👍

**Comment by hicksy** [comment]
If that resolves it for you, then hopefully it'll be the same for others in this thread (and it'll explain why we could repro the issue on our old site)

**Comment by steve-fenton-octopus** [comment]
This is brilliant - I tried to write this and had the infinite redirect issue. The version you posted above is working perfectly.

Additional note - run a full cache invalidation after associating the function - otherwise it's likely the old redirects and new redirects will clash.

Thanks for this!

**Comment by hicksy** [comment]
> This is brilliant - I tried to write this and had the infinite redirect issue. The version you posted above is working perfectly.
> 
> Additional note - run a full cache invalidation after associating the function - otherwise it's likely the old redirects and new redirects will clash.
> 
> Thanks for this!

Brilliant. Glad it helped. Hopefully useful for anyone else that had an issue.
