### ISSUE TITLE
Update to node 16 needed

### ISSUE THREAD

**Issue by IvanVilla** [sinovi/lambda-edge-remove-trailing-slash#5]
Hello, since Node.js 12 End-Of-Life (EOL) reached on April 30, 2022, this code must be update.
Are there any plans to do it?

Thank you very much!

**Comment by hicksy** [comment]
Hi Ivan - we've updated the runtime to nodejs16.x and re-deployed to the Serverless application repo (version 1.2.1 - https://serverlessrepo.aws.amazon.com/applications/us-east-1/951661612909/LambdaEdgeRemoveTrailingSlash)

**Comment by IvanVilla** [comment]
And working! Thank you very much!
