### ISSUE TITLE
Update runtime to nodejs18.x

### ISSUE THREAD

**Issue by Andrewcorre** [sinovi/lambda-edge-remove-trailing-slash#7]
Hello, since Node.js 16 End-Of-Life (EOL) reached on September 11, 2023, this code must be update.
Are there any plans to do it?

Thanks in advanced!

**Comment by jgalley** [comment]
Thanks for your message @Andrewcorre. With the release of [version 1.3.0](https://github.com/sinovi/lambda-edge-remove-trailing-slash/releases/tag/v1.3.0) we've updated this app to the `Nodejs20.x` runtime.
