### ISSUE TITLE
Open Redirect issue

### ISSUE THREAD

**Issue by matteokutufa** [sinovi/lambda-edge-remove-trailing-slash#8]
Hello,
I want to suggest to update the code adding this block due to solve a Open Redirest issue.

```
[...]
    var request = event.Records[0].cf.request;

    if (/^\/\/[^\/]+/.test(request.uri)) {
        const response = {
            status: '404',
            statusDescription: 'Not Found'
        };
        return callback(null, response);
    }

    if(request.uri !== '/' && request.uri.substr(-1) === '/') {
[...]
```

Whitout this if block if you try to navigate an url like https://www.example.com//acme.it/ (apy attention to double slashes and trailing slash) yuo will redirect to https://acme.it site.

Hoping I was helpfull I want to thank you for your code.

Best,
Matteo

**Comment by jgalley** [comment]
Hi @matteokutufa, we've included an update to resolve this as part of [version 1.3.0](https://github.com/sinovi/lambda-edge-remove-trailing-slash/releases/tag/v1.3.0) released today. 

Many thanks!
